### ISSUE TITLE
Visualization improvements

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-webui#200]
This issue is basically a continuation/iteration on https://github.com/ActivityWatch/aw-webui/issues/17

# Customizable views

 - [x] Add ability for users to create/save/load user created views (done in #233)
 - [x] Add ability to add/remove visualizations from the view (done in #233)
 - [ ] Add ability to customize the size/width of a visualization?

# Timeline

 - [ ] Allow for listing events in the combined timeline, similarly to ManicTime (#199)
 - [ ] Allow for precision (start/end) time interval selection (currently only selectable by date range, not including time)
 - [ ] Make timeline full-width (no container)
 - [ ] Group event timelines by host (partially depends on fixing hostnames for web/editor watchers)
 - [ ] Make bucket titles shorter (to give more space for actual events)

# Sunburst

 - [ ] Add labels to sunburst arcs (https://github.com/David-Desmaisons/Vue.D3.sunburst/issues/14)

# Calendar

 - [ ] A calendar-like view with the full/combined timeline, grouped by app/category
   - Might be more useful than the actual timeline
   - FullCalendar looks good: https://fullcalendar.io/
   - Previously discussed in https://github.com/ActivityWatch/aw-webui/issues/16

# Misc

 - [ ] Category colors (there should be an issue/comment about this somewhere else)

**Comment by daroczig** [comment]
Hey @ErikBjare -- first of all, hats off, this is a great project, so thanks a lot for your awesome work!

I'm working on a couple of new watchers (eg git commit hooks, email send events) and the "Customizable views" functionality would be awesome for that. I'd be happy to make some donations related to that development -- but currently, I only see general donations. Is it possible to support specific work (eg this ticket)?

Also, what's your preferred way of contributing watchers? I can just put those Python scripts in a public repo under my GH username, but let me know if you'd rather receive a PR somewhere.

**Comment by ErikBjare** [comment]
>Is it possible to support specific work (eg this ticket)?

No, unfortunately. We used to have a Bountysource thing for that purpose, but it wasn't used (and Bountysource has since kinda sold out) so we stopped using it.

There are a few other things that have priority over the customizable views, and while I can understand that you want to provide an incentive for us to implement this specific thing quicker, those other things will still come first, so you might as well make a general (preferably recurring) donation :slightly_smiling_face: 

>Also, what's your preferred way of contributing watchers? I can just put those Python scripts in a public repo under my GH username, but let me know if you'd rather receive a PR somewhere.

Just put it in a public repo. We'd be happy to link to it from https://docs.activitywatch.net/en/latest/watchers.html, just let us know by sending a PR to https://github.com/ActivityWatch/docs/ :slightly_smiling_face:

**Comment by daroczig** [comment]
Thanks -- I've just set up a general recurring payment, and will send PR after cleaning up my local repo :+1:

**Comment by NicoWeio** [comment]
Here's another feature request regarding the timeline (and probably the backend): 

Currently, when I look at e.g. the last hour, in which I was first _not-afk_, then _afk_ and then again _not-afk_ , only the middle and last entries show up in the timeline, because the first one didn't start in the specified time interval. 
I don't know how complicated it would be to let the backend make a little lookahead for every bucket to see if the previous event extends into the view.

I'm still running **v0.9.2** – let me know if this is already implemented.

**Comment by NicoWeio** [comment]
Another thing is regarding the UX when trying to figure out _exactly_ from when to when an event took place. I use this to later add entries to other time tracking services I use (SaveMyTime/Clockify).
Currently, I have to add the duration to the start timestamp manually (usually in my head). So: displaying the end date in some way would be great.

**Comment by NicoWeio** [comment]
Related: #216. Although that won't be as relevant when I can add my own views, I guess.

**Comment by ErikBjare** [comment]
>Currently, when I look at e.g. the last hour, in which I was first not-afk, then afk and then again not-afk , only the middle and last entries show up in the timeline, because the first one didn't start in the specified time interval.

@NicoWeio Sorry for the late reply. Your issue should be resolved in aw-server-rust (it'll take some time before it becomes the default server).

>Displaying the end date in some way would be great.

Fixed in https://github.com/ActivityWatch/aw-webui/commit/f0e8b4c58daacf5bf565ccdf8d888d16f931617b

>Related: #216. Although that won't be as relevant when I can add my own views, I guess.

Custom views were just merged in #233. But still relevant, I've been considering adding something search-like feature like this before.
